### PR TITLE
gemtest sample for libgem added

### PR DESCRIPTION
**Pull request by bigboss-ps3dev**
After Matt libgem commit no reason to have a sample :P. When functional libusbd will be added?

I have added a little sample to show libgem use. Some changes to compile and run fine are included in commit. Run fine on 3.55, debug over network included in sample.

You will need Eye and Move device.
Point Move directly to Eye after picture is showed on TV display and press Move button. This will calibrate your device and a nice colour will be in your Move gem.
Press triangle to begin track gyro axis x and axis y camera frame will move with your Move device.

Code with comments.

more to come...

### CODE REVIEW

**Comment by Parlane** [comment]
I am very sorry I havn't had a chance with libusbd bigboss. I will make this a high priority.

**Comment by Parlane** [comment]
There would appear to be a bug introduced in this code for the sprx, where you have replaced the u32 definitions with void\* and another pointer type. Because this is being passed to a 32bit sprx, this will have unknown consequences due to bad pointers. It may not always be noticeable but when you start trying to make them not NULL, problems will arise.

**Comment by bigboss-ps3dev** [comment]
GemVideoConvertAttribute without u32 on video_out and u32 on buffer_memory calling gemPrepareVideoConvert doesn't return 0, i suppose that for this reason video_out always is empty perhaps.

GemAttribute spurs must be aligned to 128 so i directly i put Spurs structure pointer, with other combination i had problems so i left this.

**Comment by Parlane** [comment]
And whoops, I myself managed to mess up GemVideoConvertAttribute which you fixed for me :)

**Comment by bigboss-ps3dev** [comment]
without 
gem_attr.spurs = &spurs;
gem_attr.memory=(u32)(u64)container1;

and 
void \* memory  and Spurs \* on GemAttribute definition gemInit will not return 0  and lib will not be  initalized and sample will not run fine.

Output should be this:

network debug module initialized
ready to have a lot of fun
cam return 0
move return 0
lv2MemContinerCreate() returned 0
Initializing screen...
Initializing pad...
cameraInit() returned 0
return from GemGetMemorySize 120000 size in bytes needed for move device to init libgem
lv2MemContinerCreate() for memory usage needed in libgem returned 0
preparing GemAttribute structure with sprus and memory stuff is very important align correctly spurs structure for this reason i chaged move.h to 
calling GemInit with GemAttribute structure version=2 max_connect=1 spurs=D000FBC0 memory_ptr=3F000006  
return from GemInit 0 
Preparing GemVideoConvert structure 
GemPrepareVideoConvert return 0  
GemPrepareCamera return 0 exposure set to 500 and quality to 0.5
GemReset return 0 
Found me an eye, arrr!
cameraOpenEx returned 00000000
Video dimensions: 640x480
Buffer at 30015000
Setting CameraReadEx buffer to cameraInfo buffer
GemPrepareCamera return 0 exposure set to 500 and quality to 0.5 before cameraStart
lets go!! It's time to look your face in Sony Bravia :P
Move button pressed, time to make calibration
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 5 Second set a hue value to track or let Sony choose for you :P
GemTrackHues return 0
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 3 Calibrating is in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 4 Computing colors in proccess...
status 0 Move calibrated and ready!!
Yeah Move it's running fine, light on!!!!!
Calibrating proccess finalized

**Comment by Parlane** [comment]
GemVideoConvertAttribute is perfect as far as I can see. It is the 
-  void \* memory;
-  Spurs \* spurs; //pointer to Spurs object 

Which is wrong IMO. Considering you only actually put u32 values in it:
-  gem_attr.spurs = (u32)(u64)&spurs;
-  gem_attr.memory=(u32)(u64)container1;

The prx will be accessing the top 32 bits of "memory" for the memory container, (which will be NULL) and the bottom 32bits of "memory" for the spurs object, which will be the pointer to container1.

**Pull request merged**
