### PR TITLE
Fix broken RSX samples

### PR DESCRIPTION
**Pull request by zeldin**
The fragment program functions and types now have an "_old" tacked on, which broke the compilation of the RSX samples.  Fixed this by adding the _old suffix to the sample code.

### CODE REVIEW

**Comment by shagkur** [comment]
merged.

**Comment by zeldin** [comment]
Thanks.  Although for the next time, would you please consider actually merging the commit instead of breaking it up into several spurious new commits which loses all the metadata?  That way it would also mean less work for me to get my own branch in synch with master again (now I have to back out my own commit since it will forever be considered "unmerged")...

**Comment by shagkur** [comment]
ye ye, i'll next time.

**Comment by zeldin** [comment]
Ok, thanks again.

**Pull request closed without merging**
