### PR TITLE
Review my new features lib DbgCon (debug console) & lib Screen (basic screen init) + Tests

### PR DESCRIPTION
**Pull request by bvernoux**
Adding 2 new library dbgcon & screen
Informations about library dbgcon (based on dwrfcrank console):
libdbgcon is a basic console for debugging/sample purpose
Requirements from https://github.com/HACKERCHANNEL/PSL1GHT/wiki/Framebuffer-Console-Requirements are covered
1) It must not have any dependencies on psl1ght -> No dependencies to PSL1GHT (100% portable code, requires only 32bit screen color).
2) No fixed font sizes. -> This version use fixed font size but could implement new API to load new font, will require minor change (in function con_putc()).
3) Flexible console and render target(s). -> Console size must be specified and console framebuffer can be also returned (with con_framebuffer_get()) to manage draw on graphic buffer like you want.
4) Double buffering. -> Any buffering mechanism can be used, the console write in it's own framebuffer.
5) No global variables. -> The console use "handle" object oriented API so no global variable are used and unlimited console can be created (the only limit is about font which are embedded using font[] & FONT_WIDTH/FONT_HEIGHT).
6) Transparency. -> It's not managed by console con_draw() but can be easily replaced by user to do what he want using the console framebuffer and foreground/background color.
7) Reading from the framebuffer. -> The console use it's own framebuffer in main Memory.
8) Non-Scrolling text. ->  Can be done using con_printf_xy() API.

Informations about library screen:
A very basic screen initialisation using double buffering used mainly for test purpose.

Informations about kbcon test with screen/console test with keyboard & pad support:
It is a full graphical test to validate screen/console/event using keyboard and pad.
Usage:
You shall plug an USB keyboard to use this demo and to type text in console
Press pad button X to exit
Press pad button O to printf_xy(x=0,y=0) timing informations
Press pad button /\ to printf() timing informations
Press pad button [] to change fgcolor
Press pad button SELECT to clear console framebuffer
Press pad button START to display help

### CODE REVIEW

**Comment by Parlane** [comment]
Number 2 is high on list due to the fact that without it, your stuck at either a large font on a small screen. Or a small font on a big screen... This does not meet requirements.

**Comment by bvernoux** [comment]
Can be adapted using freetype ...

**Comment by ooPo** [comment]
Is this something we can consider merging and using now, with the intent of improving font size support in the near future? Something is better than nothing at this point...

**Comment by scognito** [comment]
Someone should add some console output library...this one seems ok to me...this would eventually let some developer to start to develop as not everyone is skilled/has the possibility to use Kammy.
I made Sconsole, it is very minimal (http://scognito.wordpress.com/2010/11/07/sconsole-a-simple-function-for-printing-strings-on-ps3/) but someone even in github used it.
I vote TitanMKD though.

**Comment by ooPo** [comment]
How out of date is this code?

**Comment by scognito** [comment]
Don't know, I didn't tried dbgcon

**Pull request closed without merging**
