### PR TITLE
Mingw

### PR DESCRIPTION
**Pull request by miigotu**
I've redone this from a clean master.  Majority of the changes were to clean up compiler output so that it was easier to see and trace errors.
Signedness warnings were fixed in tools/cgcomp/source/fpparser.cpp, tools/cgcomp/include/compilerfp.h, and tools/ps3load/main.c . list::<t>::iterator->count is unsigned and in win32 send expects const char \* where linux expects const void *

PS3Py has the -cmingw set to compile with mingw if the kernel is mingw.
Sprxlinker open permissions were fixed for win32.

The sed line may need changed If it is not compatible with linux @ https://github.com/miigotu/PSL1GHT/commit/e34de2fba140b3dd98c7132cc930bc0b0f01ee74#L0L29

### CODE REVIEW

**Comment by ooPo** [comment]
I'm not a mingw user, but I took a quick look at the changes they seem fine to me.
Is that sed line still a problem?

**Comment by miigotu** [comment]
Noone has tried to use the line i changed it to from inside a makefile and checked the resulting file yet =P.

**Comment by ooPo** [comment]
Any comments on these changes?

I'll probably merge them on the weekend if nobody complains and they pass testing.

**Comment by ooPo** [comment]
Merged with some minor fixes.

**Pull request merged**
