### PR TITLE
Various fixes and improvements to cgcomp

### PR DESCRIPTION
**Pull request by zeldin**
cgcomp does not actually use libCg.so when the -a option is specified, so it makes no sense to require it.

### CODE REVIEW

**Comment by zeldin** [comment]
I fixed some bugs and added support for REP/BRK as well.  Now I am able to assemble my Mandelbrot fragment program on Linux/PPC.

**Comment by shagkur** [comment]
Thanks alot for your fixes, additions and changes to it. i just commited it to the master.

**Comment by zeldin** [comment]
Hi shagkur.

It looks like you made some mistake when you applied my changes:  The first line of CParser::ParseCond is supposed to be

<pre><code>token = ConvertCond(token,insn);</code></pre>

but on HACKERCHANNEL:master it appears as

<pre><code>token = ConvertCond(&token[1],insn);</code></pre>

which loses the first character of the condition.

It would probably have been simpler if you had just merged the commits instead of whatever you did now...  :-/

**Comment by zeldin** [comment]
Also, the code `token++;` in the parsing of o[] registers in CFPParser::ParseMaskedDstReg seems to have been lost.  Without this, the closing ] is not parsed, and so stuff like o[COLR](NE) will not work because ParseMaskedDstRegExt will get "](NE)" instead of "(NE)".

**Comment by shagkur** [comment]
Hi, sorry for the hassle. Yeah, i merged it manually and obv there happend some mistakes. Sorry again. It's fixed now.

**Comment by zeldin** [comment]
Looks all right now according to `git diff -w`.  Thanks.

**Pull request closed without merging**
