### PR TITLE
Hermes' fixes for sbrk, msgdialog, spu samples, and added libsysfs

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by ooPo** [comment]
The SPU samples were modified during a previous merge:
https://github.com/HACKERCHANNEL/PSL1GHT/commit/fc847200cf644c97df8e

Specifically, the parts this request add were removed by that merge. Which is supposed to be correct?

**Comment by zerkman** [comment]
My latest chages are correct. The removed code parts were useless and introduced dynamic memory allocation issues (as found by shagkur and verified by myself).

zerkman

**Comment by ooPo** [comment]
Okay. Once those changes get removed from this merge request I'll do the merge.

**Comment by miigotu** [comment]
Yes, I didnt realize those were removed.  I just made a clean udiff from hermes tarball and removed the stuff that would conflict.

**Comment by ooPo** [comment]
Merged!

**Pull request merged**
